### ISSUE TITLE
feature-request: postgres storage support

### ISSUE THREAD

**Issue by c-nv-s** [hyperonym/ratus#10]
please add postgres support to the storage engine options

**Comment by peakji** [comment]
We are currently implementing a in-memory storage and will work on adding relational database support when it is stable.

**Comment by peakji** [comment]
Update: the in-memory store is available in `v0.3.0`, and now we have a [roadmap](https://github.com/hyperonym/ratus#roadmap) for adding more storage engines.

**Comment by zeina1i** [comment]
Hi @peakji 
Are you going to define tasks for the roadmap items, and if we are interested,could we be involved?
Thanks

**Comment by peakji** [comment]
@zeina1i The roadmap is just a rough plan, and contributions of any kind are always welcome! 

In fact, I don't have much experience with Postgres, so I haven't started working on the relevant parts yet. If you are interested in implementing support for a new storage engine, you can refer to the [engine](https://github.com/hyperonym/ratus/tree/master/internal/engine) package. And if the test cases in [testsuite](https://github.com/hyperonym/ratus/blob/master/internal/engine/testsuite.go) all pass, then it should work properly.

**Comment by c-nv-s** [comment]
@zeina1i did you decide to have a look?

**Comment by zeina1i** [comment]
@c-nv-s unfortunately currently I don't have enough time to be involved.

**Comment by c-nv-s** [comment]
not sure why I didn't think of this earlier, but I'll see if I can test this with https://github.com/FerretDB/FerretDB sometime next week.
Hopefully it will serve as a stop-gap until the final implementation.

**Comment by c-nv-s** [comment]
just to update on this...
unfortunately it didn't work because it looks like the ferretdb team haven't yet implemented how to handle the _hint_ query functionality from mongodb yet
here is the docker-compose.yml file I used:
```
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:password@postgres:5432/ferretdb

  ratus:
    image: hyperonym/ratus:0.6.2
    restart: unless-stopped
    depends_on:
      - ferretdb
    environment:
      ENGINE: "mongodb"
      MONGODB_URI: "mongodb://ferretdb:27017"
      MONGODB_DATABASE: "ferretdb"
      MONGODB_COLLECTION: "tasks"
      MONGODB_RETENTION_PERIOD: "72h"
    ports:
      - "8000:80"

networks:
  default:
    name: ferretdb
```
and you have to remember to add the ferretdb database to your ``search_path`` when in ``psql``
I did this using: ``ALTER ROLE postgres SET search_path = "$user", public, ferretdb ;``
